Feat: Deployment Shift To AWS Server

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,12 +17,12 @@ jobs:
           mkdir -p ~/.ssh
           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan -H 147.93.110.173 >> ~/.ssh/known_hosts
+          ssh-keyscan -H 43.204.90.158 >> ~/.ssh/known_hosts
 
       - name: Deploy to Server
         env:
           DEPLOY_PATH: /home/one1app
-          DEPLOY_HOST: 147.93.110.173
+          DEPLOY_HOST: 43.204.90.158
           DEPLOY_USER: root
         run: |
           ssh $DEPLOY_USER@$DEPLOY_HOST "bash -s" << 'ENDSSH'
@@ -71,5 +71,5 @@ jobs:
         run: |
           echo "Waiting for services to start..."
           sleep 30  # Give services time to start
-          curl -I http://147.93.110.173:5173 || { echo "Validation failed: Service is not reachable"; exit 1; }
+          curl -I http://43.204.90.158:5173 || { echo "Validation failed: Service is not reachable"; exit 1; }
           echo "Validation successful: Service is up and running."
